export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FALUIRE = 'FORGOT_PASSWORD_FALUIRE';
export const FORGOT_PASSWORD_RESET_MSG = 'FORGOT_PASSWORD_RESET_MSG';

