export const GET_TEAM = 'Teams/GET_TEAM';
export const GET_TEAM_SUCCESS = 'Teams/GET_TEAM_SUCCESS';
export const GET_EMPLOYEES = 'Teams/GET_EMPLOYEES';
export const GET_UN_ASSIGNED_EMPLOYEES = 'Teams/GET_UN_ASSIGNED_EMPLOYEES';
export const GET_EMPLOYEES_SUCCESS = 'Teams/GET_EMPLOYEES_SUCCESS';
export const GET_UN_ASSIGNED_EMPLOYEES_SUCCESS='Teams/GET_UN_ASSIGNED_EMPLOYEES_SUCCESS'
export const REMOVE_TEAM_MEMBER='Teams/REMOVE_TEAM_MEMBER'
export const ADD_TEAM_MEMBER='Teams/ADD_TEAM_MEMBER'

export const CREATE_TEAM = 'Teams/CREATE_TEAM';
export const CREATE_TEAM_FAILURE = 'Teams/CREATE_TEAM_FAILURE';
export const DELETE_TEAM = 'Teams/DELETE_TEAM';
export const RESET = 'Teams/RESET';



