# Generated by Django 2.2.27 on 2022-05-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_teammembershiprecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembershiprecord',
            name='record_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
